pages:
  stage: deploy
  image: ubuntu:latest
  script:
  - apt-get update -y
  - apt-get install -y mkdocs
  - mkdir ./public
  - cd HIG41
  - mkdocs build
  - cp -Rv ./site ../public
  - cd ..
  artifacts:
    paths:
    - public
  only:
    - master
