site_name: GNOME Human Interface Guidelines

nav:
  - Introduction:
    - Applicability of the HIG: applicability.md
    - A vision for apps: vision.md
  - Guidelines:
    - App identity: guidelines/app-identity.md
    - App basics: guidelines/app-basics.md
    - Writing style: guidelines/writing-style.md
    - Visuals: guidelines/visuals.md
    - Input: guidelines/input.md
    - Typography: guidelines/typography.md
    - Scaling and responsiveness: guidelines/responsive.md
  - Containers:
    - Header bars: containers/headerbar.md
    - Dialogs: containers/dialog.md
    - Grids: containers/grid.md
    - Lists: containers/list.md
  - Navigation:
    - Browsing: nav/browse.md
    - View switchers: nav/view-switch.md
    - Tabs: nav/tab.md
    - Sidebars: nav/sidebar.md
    - Search: nav/search.md
  - Feedback:
    - Notifications: feedback/notification.md
    - In-app notifications: feedback/in-app-not.md
    - Info bars: feedback/info-bar.md
    - Progress bars: feedback/progress-bar.md
    - Spinners: feedback/spinner.md
  - Controls:
    - Buttons: controls/button.md
    - Check boxes: controls/check.md
    - Dropdown lists: controls/dropdown.md
    - Floating controls: controls/floating.md
    - Menus: controls/menu.md
    - Placeholders: controls/placeholder.md
    - Popovers: controls/popover.md
    - Radio buttons: controls/radio.md
    - Sliders: controls/slider.md
    - Spin buttons: controls/spinbutton.md
    - Switches: controls/switch.md
    - Text fields: controls/text.md
  - Reference:
    - Standard touch behaviours: reference/touch.md
    - Standard keyboard shortcuts: reference/keyboard.md
theme:
  name: null
  language: en
  custom_dir: 'gnome'
  direction:
  # Feature flags for functionality that alters behavior significantly, and thus
  # may be a matter of taste
  features: []
  # Sets the primary and accent color palettes as defined in the Material Design
  # documentation - possible values can be looked up in the getting started guide
  palette:
    # Primary color used for header, sidebar and links, default: indigo
    primary: grey
    # Accent color for highlighting user interaction, default: indigo
    accent:
  # Fonts used by Material, automatically loaded from Google Fonts - see the site
  # for a list of available fonts
  font:
    # Default font for text
    text: Cantarell
    # Fixed-width font for code listings
    code: Source Code Pro

  # From Material 5.x on, icons are inlined into the HTML and CSS as SVGs. Some
  # icons that are part of the HTML can be configured and replaced
  icon:
    logo: gnome/gnome
  # Favicon to be rendered
  favicon: assets/images/favicon.png
  # Material includes the search in the header as a partial, not as a separate
  # template, so it's correct that search.html is missing
  include_search_page: false
  # Material doesn't use MkDocs search functionality but provides its own. For
  # this reason, only the search index needs to be built
  search_index_only: true
  # Static pages to build
  static_templates:
    - 404.html
